### PR TITLE
Swipe options xd-

### PR DESCRIPTION
**Pull request by SPLCoding**

### CODE REVIEW

**Comment by SPLCoding** [comment]
actually saying this before a problem, the code is originally by saw, but i fixed something for not having compiling errors :b

**Comment by MaysLastPlayGithub** [comment]
Did you tested it?

**Comment by RenTheSylvee** [comment]
> Did you tested it?

yeah i tested it before

**Comment by RenTheSylvee** [comment]
basically this thing is for the editors but i forgot to specify because the hour i pull requested this idbsidjdi

**Comment by MaysLastPlayGithub** [comment]
Ok....

**Pull request merged**
